#!/bin/bash
echo Input Number of Commits Needed : 
read number
if ! [[ $number =~ ^[0-9]+$ ]]
    then
        echo "Sorry integers only"
else
git init
for (( c=0; c<number; c++ ))
do  
   echo '.' >> rndmfle.kzc
   git add .
   git commit -m "Commit Has Been Made"
done
echo ""
echo ""
echo " $number commits have been made"
rm rndmfle.kzc
fi
echo ""
echo "Press Enter To Exit"
read dd
