#!/bin/bash
echo Input Number of Previous Days to Randomly Commit : 
read number
echo Enter Maximum number of commits a day :
read max
if ! [[ $max =~ ^[0-9]+$ ]]
    then
        echo "Sorry integers only"
else
    if ! [[ $number =~ ^[0-9]+$ ]]
        then
            echo "Sorry integers only"
    else
    git init
    for (( c=0; c<number; c++ ))
    do  
        for (( d=0; d<max; d++ ))
        do  
            if [ "$[RANDOM%2]"=="1" ]
            then
                if [ $[RANDOM%2] == "1" ]
                then
                    echo '.' >> rndmfle.kzc
                    git add .
                    git commit -m "Commit Has Been Made" --date="$c"
                fi
            fi
        done
    done
    echo ""
    echo ""
    echo " Commits have been backdated to the past $number days."
    rm rndmfle.kzc
    fi
fi
echo ""
echo "Press Enter To Exit"
read dd 

